name: Dokcer build

on:
  push:
    branches: [mlabs/build]
  pull_request:
    branches: [mlabs/build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Docker meta
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: 561718152453.dkr.ecr.us-east-1.amazonaws.com/metaplex
      #     tags: |
      #       type=sha
      #     flavor: |
      #       latest=true

      # - name: Run docker build
      #   id: build-base-image
      #   uses: docker/build-push-action@v2
      #   with:
      #     file: Dockerfile
      #     tags: ${{ steps.meta.outputs.tags }}
      #     push: true

      - name: Get ECR password (temporary)
        id: get-ecr-password
        run: echo "::set-output name=password::$(aws ecr get-login-password)"

      - name: Build & Push image
        uses: docker/build-push-action@v1
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          repository: metaplex
          username: AWS
          password: ${{ steps.get-ecr-password.outputs.password }}  # temporary
          add_git_labels: true
          tag_with_ref: true
